### ISSUE TITLE
About Japanese Translation

### ISSUE THREAD

**Issue by morizotter** [mgechev/angularjs-in-patterns#11]
Hi,

I found out that your document is very valuable and to understand it deeply, I forked it and translated it to Japanese :) - I saw your web site's the right-upper corder "fork me" ribbon!

Translated Article is this: 
https://github.com/morizotter/angularjs-in-patterns/blob/translation-japanese/README-ja-jp.md

I think it is good for Japanese angularJS users to read this article - they can read English but if it's a translation, it becomes a good entrance to the article. 

## Question

And I wonder how I will treat this translation. If you are Ok, merge this translation into your repository like `angularjs-style-guide`. In this case, I'll send you pr. 

Or, I'll treat it as just as a forked repository :) 

Thanks for your article!

**Comment by mgechev** [comment]
I'd love to merge it into the main branch. Thank you for your translation!
