### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by manekinekko** [mgechev/angularjs-in-patterns#20]
Hi @mgechev 
Great work here. I was thinking doing the same, having a repo with all common pattern used in AngularJS. But you did you bro!!! :+1: 

So I thought I could give u a hand by translating your doc into French. What do u think? Does this interest you?

**Comment by mgechev** [comment]
It will be awesome! So far the article has [Russian](http://habrahabr.ru/post/250149/) and [Japanese](https://github.com/mgechev/angularjs-in-patterns/blob/master/i18n/README-ja-jp.md) translations.

I'm also planning to extend it with Angular 2 patterns (already started [here](https://github.com/mgechev/angularjs-in-patterns/tree/m-ng2)), however I have some extra work these days.

**Comment by manekinekko** [comment]
Perfect. I will add this to my todo list then.

**Comment by mgechev** [comment]
@manekinekko thanks for the translation! I believe we can close this issue.
