### ISSUE TITLE
Table of content issues

### ISSUE THREAD

**Issue by carlosliu** [mgechev/angularjs-in-patterns#23]
1. `Data Mapper` (line 1019) and `Observer Pattern as an External Service` (line 1095) should have `#### ` in front of them, rather than `###`.
2. Should *Interpreter* be a subsection of *Directives*? It's a pattern, instead of an AngularJS component. The DSL interpreter could be a part of directives content.

**Comment by mgechev** [comment]
Yes, you're correct for both! Thanks for pointing them out!
