### ISSUE TITLE
Automate the building process

### ISSUE THREAD

**Issue by mgechev** [mgechev/angularjs-in-patterns#7]
Automate the building process with [markdown-pdf](https://www.npmjs.org/package/markdown-pdf).

**Comment by manekinekko** [comment]
I started this enhancement, but I had few questions:

1) What is exactly the purpose of this command? I mean I understand the regex replacement, but why?
```perl 
perl -i -0777 -pe 's/(<!--toc-->).*(<!--endtoc-->)/'"$"'$2/s' ./temp/README.md
```

2) Why do you need to move everything inside the ./temp dir before running generate-md?

**Comment by mgechev** [comment]
1. I think I was too lazy to fix the links in the table of content so I just removed it.
2. I prefer to have a working directory in order to not screw something up in the root of the project

The gulpfile you added looks great! Yeah, I cheated with the PDF in the `build` directory and built it manually.

**Comment by mgechev** [comment]
I think we can close this one :smile:

**Comment by manekinekko** [comment]
Awesome! Time to start the translation then ;)
See u in a couple of days...
